#+TITLE: org-bookmark-heading
#+PROPERTY: LOGGING nil

[[http://melpa.org/#/org-bookmark-heading][file:http://melpa.org/packages/org-bookmark-heading-badge.svg]] [[http://stable.melpa.org/#/org-bookmark-heading][file:http://stable.melpa.org/packages/org-bookmark-heading-badge.svg]]

This library provides Emacs bookmark support for Org mode.  You can bookmark headings in Org files and jump to them using standard Emacs bookmark commands.

It seems like this package should be named ~org-bookmark~, but a package by that name already exists in ~org-mode/contrib~ which lets Org links point to Emacs bookmarks.

It also seems like this should be built-in to Org.  Someday it may be upstreamed...

* Installation

If you've installed from MELPA (or with a package system like Straight or Quelpa), you're done.  Then you can customize =org-bookmark-jump-indirect= if you like.

To install manually, put ~org-bookmark-heading.el~ in your ~load-path~ and require the feature in your init file:

#+BEGIN_SRC elisp
(require 'org-bookmark-heading)
#+END_SRC

* Usage

Use the standard Emacs bookmark commands, =C-x r m=, etc.

If you use Helm, you can jump to Org bookmarks in an indirect buffer by pressing =<C-return>= in the Helm buffer, or by choosing the action from the list.

You can also customize the variable =org-bookmark-jump-indirect= to make Org bookmarks always open in indirect buffers.

* Changelog

** 1.3-pre

Nothing new yet.

** 1.2

*Additions*
+ Option ~org-bookmark-heading-make-ids~ controls whether a new ID is created when none exists.

*Changes*
+ Bookmark records always include the filename, outline path, and an existing ID property.
+ When a bookmark is created in an indirect buffer, the restored bookmark will use an indirect buffer.
+ Lexical binding is enabled.
+ Library =f= is no longer used.
+ Symbols are now properly prefixed with the package name, and obsolete aliases to the former names are defined.
+ Various small improvements.

** 1.1

*Additions*
+  Proper customization group, ~org-bookmark-heading~.
+  Customizeable filename function, ~org-bookmark-heading-filename-fn~.

*Changes*
+  Use ~org-link-display-format~ instead of custom function.
+  By default, add parent directory to displayed filename.

** 1.0.0

Initial stable release.

* Credits

+ Thanks to [[https://github.com/purcell][Steve Purcell]] for his advice on several improvements.
+ Thanks to [[https://github.com/mm--][Joshua Moller-Mara]] for his patch improving robustness.
+ Thanks to Nicolas Goaziou for suggesting several improvements.

* License

GPLv3
